#!/bin/bash
#Check if CPU usage is critical (>= 90) 
read -p " enter your cpu usage number : " cpu_usage
if [ $cpu_usage -ge 90 ]
then 
   echo " cpu usage is critical "
else
   echo " cpu usage is moderate "
fi  
